### ISSUE TITLE
What distros does this work on?

### ISSUE THREAD

**Issue by FreddyFeuerstein** [rxrbln/xf86-video-ps3#3]
I would like to use my ps3 as a media center and therefore need a working graphics driver. I have tried compiling this on red ribbon and debian sid with manually upgraded gcc and cmake and on the 4.18 and 5.14 kernel but all of the distros and kernel versions ive tried so far do not successfully compile. can anyone help me?

**Comment by Badprt23** [comment]
Logs would be helpfull, i also wanted to try doing this but for ubuntu yakkety.

**Comment by Badprt23** [comment]
And how can u boot a newer kernel like 5.14 as there was a kernel abi breakage affecting kexec in petitboot, did u compile a new petitboot image?

**Comment by rxrbln** [comment]
Github issues are no support forum. Instead of spending hours, days or weeks re-creating what was already solved, I would suggest simply using the probably only Linux distribution still supporting the ps3: https://t2sde.org There also is a discord server to help each other: https://discord.gg/PSaBH5C
